GO ?= go
SQLC ?= sqlc
MIGRATE ?= migrate
DB_URL ?=

.PHONY: fmt vet test tidy run sqlc-generate migrate-create migrate-up migrate-down migrate-version module

fmt:
	$(GO) fmt ./...

vet:
	$(GO) vet ./...

test:
	$(GO) test ./... -race

tidy:
	$(GO) mod tidy

run:
	$(GO) run .

sqlc-generate:
	$(SQLC) generate

migrate-create:
	@if [ -z "$(NAME)" ]; then echo "NAME is required"; exit 1; fi
	$(MIGRATE) create -ext sql -dir db/migrations -seq $(NAME)

migrate-up:
	@if [ -z "$(DB_URL)" ]; then echo "DB_URL is required"; exit 1; fi
	POSTGRES_ENABLED=true POSTGRES_URL="$(DB_URL)" $(GO) run ./cmd/migrate up

migrate-down:
	@if [ -z "$(DB_URL)" ]; then echo "DB_URL is required"; exit 1; fi
	POSTGRES_ENABLED=true POSTGRES_URL="$(DB_URL)" $(GO) run ./cmd/migrate down --steps=1

migrate-version:
	@if [ -z "$(DB_URL)" ]; then echo "DB_URL is required"; exit 1; fi
	POSTGRES_ENABLED=true POSTGRES_URL="$(DB_URL)" $(GO) run ./cmd/migrate version

module:
	$(GO) run ./cmd/modulegen --name "$(name)" --force "$(force)"