-- Code generated by modulesync. DO NOT EDIT.
-- Source: internal/modules/system/db/schema.sql

CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
