// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO users (email, password_hash, role, permissions, status, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, role, permissions, status, created_at, updated_at, tenant_id, account_version, totp_enabled
`

type CreateAuthUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         pgtype.Text `json:"role"`
	Permissions  int64       `json:"permissions"`
	Status       string      `json:"status"`
	TenantID     string      `json:"tenant_id"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAuthUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Permissions,
		arg.Status,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AccountVersion,
		&i.TotpEnabled,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, email, password_hash, role, permissions, status, created_at, updated_at, tenant_id, account_version, totp_enabled
FROM users
WHERE id = $1
`

func (q *Queries) GetAuthUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AccountVersion,
		&i.TotpEnabled,
	)
	return i, err
}

const getAuthUserByIDInTenant = `-- name: GetAuthUserByIDInTenant :one
SELECT id, email, password_hash, role, permissions, status, created_at, updated_at, tenant_id, account_version, totp_enabled
FROM users
WHERE tenant_id = $1 AND id = $2
`

type GetAuthUserByIDInTenantParams struct {
	TenantID string      `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Tenant-scoped lookup for goauth.TenantAwareUserProvider. The tenant
// predicate is enforced in SQL; a user in another tenant is not found.
func (q *Queries) GetAuthUserByIDInTenant(ctx context.Context, arg GetAuthUserByIDInTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByIDInTenant, arg.TenantID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AccountVersion,
		&i.TotpEnabled,
	)
	return i, err
}

const getAuthUserByLogin = `-- name: GetAuthUserByLogin :one
SELECT id, email, password_hash, role, permissions, status, created_at, updated_at, tenant_id, account_version, totp_enabled
FROM users
WHERE email = $1
`

func (q *Queries) GetAuthUserByLogin(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByLogin, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AccountVersion,
		&i.TotpEnabled,
	)
	return i, err
}

const getAuthUserByLoginInTenant = `-- name: GetAuthUserByLoginInTenant :one
SELECT id, email, password_hash, role, permissions, status, created_at, updated_at, tenant_id, account_version, totp_enabled
FROM users
WHERE tenant_id = $1 AND email = $2
`

type GetAuthUserByLoginInTenantParams struct {
	TenantID string `json:"tenant_id"`
	Email    string `json:"email"`
}

// Tenant-scoped lookup for goauth.TenantAwareUserProvider. The tenant
// predicate is enforced in SQL; an identifier in another tenant is not found.
func (q *Queries) GetAuthUserByLoginInTenant(ctx context.Context, arg GetAuthUserByLoginInTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByLoginInTenant, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AccountVersion,
		&i.TotpEnabled,
	)
	return i, err
}

const updateAuthUserPasswordHash = `-- name: UpdateAuthUserPasswordHash :one
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
RETURNING id
`

type UpdateAuthUserPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateAuthUserPasswordHash(ctx context.Context, arg UpdateAuthUserPasswordHashParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateAuthUserPasswordHash, arg.ID, arg.PasswordHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateAuthUserStatus = `-- name: UpdateAuthUserStatus :one
UPDATE users SET status = $2, account_version = account_version + 1, updated_at = NOW() WHERE id = $1
RETURNING id, email, password_hash, role, permissions, status, created_at, updated_at, tenant_id, account_version, totp_enabled
`

type UpdateAuthUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Keyed by the globally unique user id. goAuth resolves the user through the
// tenant-scoped lookup before any status transition, and email-verification
// confirm deliberately runs under the challenge's tenant rather than the
// request's, so this update must not re-scope by the request tenant.
// goAuth requires account_version to advance on every status transition.
func (q *Queries) UpdateAuthUserStatus(ctx context.Context, arg UpdateAuthUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAuthUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AccountVersion,
		&i.TotpEnabled,
	)
	return i, err
}
