// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO users (email, password_hash, role, permissions, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, role, permissions, status, created_at, updated_at
`

type CreateAuthUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         pgtype.Text `json:"role"`
	Permissions  int64       `json:"permissions"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAuthUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Permissions,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, email, password_hash, role, permissions, status, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetAuthUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByLogin = `-- name: GetAuthUserByLogin :one
SELECT id, email, password_hash, role, permissions, status, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetAuthUserByLogin(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByLogin, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuthUserPasswordHash = `-- name: UpdateAuthUserPasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAuthUserPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateAuthUserPasswordHash(ctx context.Context, arg UpdateAuthUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateAuthUserStatus = `-- name: UpdateAuthUserStatus :one
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, email, password_hash, role, permissions, status, created_at, updated_at
`

type UpdateAuthUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAuthUserStatus(ctx context.Context, arg UpdateAuthUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAuthUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
