// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_mfa.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceUserTOTPCounter = `-- name: AdvanceUserTOTPCounter :one
UPDATE user_totp t
SET last_used_counter = $1, updated_at = NOW()
FROM users u
WHERE u.id = t.user_id
  AND t.user_id = $2
  AND t.last_used_counter < $1
  AND ($3::text IS NULL OR u.tenant_id = $3::text)
RETURNING t.user_id
`

type AdvanceUserTOTPCounterParams struct {
	Counter  int64       `json:"counter"`
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.Text `json:"tenant_id"`
}

// Only moves the counter forward, so two concurrent verifications of the same
// code cannot both succeed (replay protection holds under races).
func (q *Queries) AdvanceUserTOTPCounter(ctx context.Context, arg AdvanceUserTOTPCounterParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, advanceUserTOTPCounter, arg.Counter, arg.UserID, arg.TenantID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const consumeBackupCode = `-- name: ConsumeBackupCode :execrows
UPDATE user_backup_codes b
SET used_at = NOW()
FROM users u
WHERE u.id = b.user_id
  AND b.user_id = $1
  AND b.code_hash = $2
  AND b.used_at IS NULL
  AND ($3::text IS NULL OR u.tenant_id = $3::text)
`

type ConsumeBackupCodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash []byte      `json:"code_hash"`
	TenantID pgtype.Text `json:"tenant_id"`
}

// Atomic single use: the row lock plus the used_at IS NULL predicate mean two
// concurrent consumes of the same code cannot both report success.
func (q *Queries) ConsumeBackupCode(ctx context.Context, arg ConsumeBackupCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeBackupCode, arg.UserID, arg.CodeHash, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableUserTOTP = `-- name: DisableUserTOTP :one
WITH target AS (
    SELECT users.id AS target_id FROM users
    WHERE users.id = $1
      AND ($2::text IS NULL OR users.tenant_id = $2::text)
), deleted_totp AS (
    DELETE FROM user_totp WHERE user_id IN (SELECT target_id FROM target)
), deleted_codes AS (
    DELETE FROM user_backup_codes WHERE user_id IN (SELECT target_id FROM target)
)
UPDATE users u
SET totp_enabled = FALSE,
    account_version = u.account_version + CASE WHEN u.totp_enabled THEN 1 ELSE 0 END,
    updated_at = NOW()
FROM target
WHERE u.id = target.target_id
RETURNING u.id
`

type DisableUserTOTPParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.Text `json:"tenant_id"`
}

// Removes the TOTP secret and all backup codes, clears users.totp_enabled and
// advances account_version when TOTP was enabled.
func (q *Queries) DisableUserTOTP(ctx context.Context, arg DisableUserTOTPParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, disableUserTOTP, arg.UserID, arg.TenantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserTOTP = `-- name: GetUserTOTP :one

SELECT t.secret_ciphertext, t.verified, t.last_used_counter, u.totp_enabled
FROM user_totp t
JOIN users u ON u.id = t.user_id
WHERE t.user_id = $1
  AND ($2::text IS NULL OR u.tenant_id = $2::text)
`

type GetUserTOTPParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.Text `json:"tenant_id"`
}

type GetUserTOTPRow struct {
	SecretCiphertext []byte `json:"secret_ciphertext"`
	Verified         bool   `json:"verified"`
	LastUsedCounter  int64  `json:"last_used_counter"`
	TotpEnabled      bool   `json:"totp_enabled"`
}

// TOTP and backup-code persistence for goAuth's UserProvider MFA methods.
//
// Every query takes an optional tenant_id. NULL (tenancy disabled) scopes by
// user id only; a value restricts the operation to users in that tenant, so a
// user id from another tenant matches nothing. Each operation is a single
// statement, so it is atomic without an explicit transaction.
func (q *Queries) GetUserTOTP(ctx context.Context, arg GetUserTOTPParams) (GetUserTOTPRow, error) {
	row := q.db.QueryRow(ctx, getUserTOTP, arg.UserID, arg.TenantID)
	var i GetUserTOTPRow
	err := row.Scan(
		&i.SecretCiphertext,
		&i.Verified,
		&i.LastUsedCounter,
		&i.TotpEnabled,
	)
	return i, err
}

const listUnusedBackupCodes = `-- name: ListUnusedBackupCodes :many
SELECT b.code_hash
FROM user_backup_codes b
JOIN users u ON u.id = b.user_id
WHERE b.user_id = $1
  AND b.used_at IS NULL
  AND ($2::text IS NULL OR u.tenant_id = $2::text)
ORDER BY b.id
`

type ListUnusedBackupCodesParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.Text `json:"tenant_id"`
}

func (q *Queries) ListUnusedBackupCodes(ctx context.Context, arg ListUnusedBackupCodesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listUnusedBackupCodes, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var code_hash []byte
		if err := rows.Scan(&code_hash); err != nil {
			return nil, err
		}
		items = append(items, code_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserTOTPVerified = `-- name: MarkUserTOTPVerified :one
UPDATE user_totp t
SET verified = TRUE, updated_at = NOW()
FROM users u
WHERE u.id = t.user_id
  AND t.user_id = $1
  AND ($2::text IS NULL OR u.tenant_id = $2::text)
RETURNING t.user_id
`

type MarkUserTOTPVerifiedParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.Text `json:"tenant_id"`
}

func (q *Queries) MarkUserTOTPVerified(ctx context.Context, arg MarkUserTOTPVerifiedParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markUserTOTPVerified, arg.UserID, arg.TenantID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const replaceBackupCodes = `-- name: ReplaceBackupCodes :execrows
WITH target AS (
    SELECT users.id AS target_id FROM users
    WHERE users.id = $2
      AND ($3::text IS NULL OR users.tenant_id = $3::text)
), deleted AS (
    DELETE FROM user_backup_codes WHERE user_id IN (SELECT target_id FROM target)
)
INSERT INTO user_backup_codes (user_id, code_hash)
SELECT target.target_id, code_hash
FROM target, unnest($1::bytea[]) AS code_hash
`

type ReplaceBackupCodesParams struct {
	CodeHashes [][]byte    `json:"code_hashes"`
	UserID     pgtype.UUID `json:"user_id"`
	TenantID   pgtype.Text `json:"tenant_id"`
}

// Deletes every existing code and inserts the new set in one statement.
func (q *Queries) ReplaceBackupCodes(ctx context.Context, arg ReplaceBackupCodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceBackupCodes, arg.CodeHashes, arg.UserID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertUserTOTPSecret = `-- name: UpsertUserTOTPSecret :one
WITH target AS (
    SELECT users.id AS target_id FROM users
    WHERE users.id = $1
      AND ($2::text IS NULL OR users.tenant_id = $2::text)
), upsert AS (
    INSERT INTO user_totp (user_id, secret_ciphertext)
    SELECT target_id, $3::bytea FROM target
    ON CONFLICT (user_id) DO UPDATE
        SET secret_ciphertext = EXCLUDED.secret_ciphertext, updated_at = NOW()
    RETURNING user_id, verified
)
UPDATE users u
SET totp_enabled = upsert.verified,
    account_version = u.account_version + CASE WHEN u.totp_enabled <> upsert.verified THEN 1 ELSE 0 END,
    updated_at = NOW()
FROM upsert
WHERE u.id = upsert.user_id
RETURNING u.id
`

type UpsertUserTOTPSecretParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	TenantID         pgtype.Text `json:"tenant_id"`
	SecretCiphertext []byte      `json:"secret_ciphertext"`
}

// Stores the (encrypted) secret and syncs users.totp_enabled to the verified
// flag, advancing account_version when the enabled state flips. Mirrors
// goAuth's EnableTOTP contract: setup stores an unverified secret (TOTP stays
// off); after MarkUserTOTPVerified the same call turns TOTP on.
func (q *Queries) UpsertUserTOTPSecret(ctx context.Context, arg UpsertUserTOTPSecretParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUserTOTPSecret, arg.UserID, arg.TenantID, arg.SecretCiphertext)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
