// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_mfa.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceUserTOTPCounter = `-- name: AdvanceUserTOTPCounter :one
UPDATE user_totp t
SET last_used_counter = $1, updated_at = NOW()
FROM users u
WHERE u.id = t.user_id
  AND t.user_id = $2
  AND t.last_used_counter < $1
RETURNING t.user_id
`

type AdvanceUserTOTPCounterParams struct {
	Counter int64       `json:"counter"`
	UserID  pgtype.UUID `json:"user_id"`
}

// Only moves the counter forward, so two concurrent verifications of the same
// code cannot both succeed (replay protection holds under races).
func (q *Queries) AdvanceUserTOTPCounter(ctx context.Context, arg AdvanceUserTOTPCounterParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, advanceUserTOTPCounter, arg.Counter, arg.UserID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const consumeBackupCode = `-- name: ConsumeBackupCode :execrows
UPDATE user_backup_codes b
SET used_at = NOW()
FROM users u
WHERE u.id = b.user_id
  AND b.user_id = $1
  AND b.code_hash = $2
  AND b.used_at IS NULL
`

type ConsumeBackupCodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash []byte      `json:"code_hash"`
}

// Atomic single use: the row lock plus the used_at IS NULL predicate mean two
// concurrent consumes of the same code cannot both report success.
func (q *Queries) ConsumeBackupCode(ctx context.Context, arg ConsumeBackupCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeBackupCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBackupCodes = `-- name: DeleteBackupCodes :execrows
DELETE FROM user_backup_codes
WHERE user_id IN (
    SELECT users.id FROM users
    WHERE users.id = $1
)
`

// First half of replacing a user's backup codes. Run it and InsertBackupCodes
// in one transaction: a single statement cannot do both because the unique
// (user_id, code_hash) constraint rejects re-inserting a hash the same
// statement deletes.
func (q *Queries) DeleteBackupCodes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackupCodes, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableUserTOTP = `-- name: DisableUserTOTP :one
WITH target AS (
    SELECT users.id AS target_id FROM users
    WHERE users.id = $1
), deleted_totp AS (
    DELETE FROM user_totp WHERE user_id IN (SELECT target_id FROM target)
), deleted_codes AS (
    DELETE FROM user_backup_codes WHERE user_id IN (SELECT target_id FROM target)
)
UPDATE users u
SET totp_enabled = FALSE,
    account_version = u.account_version + CASE WHEN u.totp_enabled THEN 1 ELSE 0 END,
    updated_at = NOW()
FROM target
WHERE u.id = target.target_id
RETURNING u.id
`

// Removes the TOTP secret and all backup codes, clears users.totp_enabled and
// advances account_version when TOTP was enabled.
func (q *Queries) DisableUserTOTP(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, disableUserTOTP, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserTOTP = `-- name: GetUserTOTP :one

SELECT t.secret_ciphertext, t.verified, t.last_used_counter, u.totp_enabled
FROM user_totp t
JOIN users u ON u.id = t.user_id
WHERE t.user_id = $1
`

type GetUserTOTPRow struct {
	SecretCiphertext []byte `json:"secret_ciphertext"`
	Verified         bool   `json:"verified"`
	LastUsedCounter  int64  `json:"last_used_counter"`
	TotpEnabled      bool   `json:"totp_enabled"`
}

// TOTP and backup-code persistence for goAuth's UserProvider MFA methods.
//
// Every query is keyed by the globally unique user id. goAuth resolves the
// user through its own lookup before it calls the provider with that id, and
// the endpoints only ever pass the authenticated principal's id, so no query
// needs a further scope. Each operation is a single statement, so it is atomic
// without an explicit transaction, except ReplaceBackupCodes, which is a
// DeleteBackupCodes + InsertBackupCodes pair that the caller must run inside
// one transaction (the repository refuses to run outside one).
func (q *Queries) GetUserTOTP(ctx context.Context, userID pgtype.UUID) (GetUserTOTPRow, error) {
	row := q.db.QueryRow(ctx, getUserTOTP, userID)
	var i GetUserTOTPRow
	err := row.Scan(
		&i.SecretCiphertext,
		&i.Verified,
		&i.LastUsedCounter,
		&i.TotpEnabled,
	)
	return i, err
}

const insertBackupCodes = `-- name: InsertBackupCodes :execrows
INSERT INTO user_backup_codes (user_id, code_hash)
SELECT users.id, code_hash
FROM users, unnest($1::bytea[]) AS code_hash
WHERE users.id = $2
`

type InsertBackupCodesParams struct {
	CodeHashes [][]byte    `json:"code_hashes"`
	UserID     pgtype.UUID `json:"user_id"`
}

// Second half of replacing a user's backup codes. Inserts nothing when the user
// does not exist.
func (q *Queries) InsertBackupCodes(ctx context.Context, arg InsertBackupCodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBackupCodes, arg.CodeHashes, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUnusedBackupCodes = `-- name: ListUnusedBackupCodes :many
SELECT b.code_hash
FROM user_backup_codes b
JOIN users u ON u.id = b.user_id
WHERE b.user_id = $1
  AND b.used_at IS NULL
ORDER BY b.id
`

func (q *Queries) ListUnusedBackupCodes(ctx context.Context, userID pgtype.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listUnusedBackupCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var code_hash []byte
		if err := rows.Scan(&code_hash); err != nil {
			return nil, err
		}
		items = append(items, code_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTOTPSecrets = `-- name: ListUserTOTPSecrets :many
SELECT t.user_id, t.secret_ciphertext
FROM user_totp t
WHERE $1::uuid IS NULL OR t.user_id > $1::uuid
ORDER BY t.user_id
LIMIT $2
`

type ListUserTOTPSecretsParams struct {
	AfterUserID pgtype.UUID `json:"after_user_id"`
	RowLimit    int32       `json:"row_limit"`
}

type ListUserTOTPSecretsRow struct {
	UserID           pgtype.UUID `json:"user_id"`
	SecretCiphertext []byte      `json:"secret_ciphertext"`
}

// Keyset-paginated scan of every stored ciphertext for the
// rotatetotpkey command. Pass a NULL after_user_id for the first page.
func (q *Queries) ListUserTOTPSecrets(ctx context.Context, arg ListUserTOTPSecretsParams) ([]ListUserTOTPSecretsRow, error) {
	rows, err := q.db.Query(ctx, listUserTOTPSecrets, arg.AfterUserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTOTPSecretsRow{}
	for rows.Next() {
		var i ListUserTOTPSecretsRow
		if err := rows.Scan(&i.UserID, &i.SecretCiphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserTOTPVerified = `-- name: MarkUserTOTPVerified :one
UPDATE user_totp t
SET verified = TRUE, updated_at = NOW()
FROM users u
WHERE u.id = t.user_id
  AND t.user_id = $1
RETURNING t.user_id
`

func (q *Queries) MarkUserTOTPVerified(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markUserTOTPVerified, userID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const rotateUserTOTPSecret = `-- name: RotateUserTOTPSecret :execrows
UPDATE user_totp t
SET secret_ciphertext = $1::bytea, updated_at = NOW()
FROM users u
WHERE u.id = t.user_id
  AND t.user_id = $2
  AND t.secret_ciphertext = $3::bytea
`

type RotateUserTOTPSecretParams struct {
	NextCiphertext []byte      `json:"next_ciphertext"`
	UserID         pgtype.UUID `json:"user_id"`
	PrevCiphertext []byte      `json:"prev_ciphertext"`
}

// Compare-and-swap for key rotation: replaces the stored ciphertext only if it
// still equals prev_ciphertext, so a concurrent enable/disable/re-enroll is
// never overwritten with a stale re-encryption. Touches no other state (the
// verified flag, users.totp_enabled and account_version are unchanged).
func (q *Queries) RotateUserTOTPSecret(ctx context.Context, arg RotateUserTOTPSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateUserTOTPSecret, arg.NextCiphertext, arg.UserID, arg.PrevCiphertext)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertUserTOTPSecret = `-- name: UpsertUserTOTPSecret :one
WITH target AS (
    SELECT users.id AS target_id FROM users
    WHERE users.id = $1
), upsert AS (
    INSERT INTO user_totp (user_id, secret_ciphertext)
    SELECT target_id, $2::bytea FROM target
    ON CONFLICT (user_id) DO UPDATE
        SET secret_ciphertext = EXCLUDED.secret_ciphertext, updated_at = NOW()
    RETURNING user_id, verified
)
UPDATE users u
SET totp_enabled = upsert.verified,
    account_version = u.account_version + CASE WHEN u.totp_enabled <> upsert.verified THEN 1 ELSE 0 END,
    updated_at = NOW()
FROM upsert
WHERE u.id = upsert.user_id
RETURNING u.id
`

type UpsertUserTOTPSecretParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	SecretCiphertext []byte      `json:"secret_ciphertext"`
}

// Stores the (encrypted) secret and syncs users.totp_enabled to the verified
// flag, advancing account_version when the enabled state flips. Mirrors
// goAuth's EnableTOTP contract: setup stores an unverified secret (TOTP stays
// off); after MarkUserTOTPVerified the same call turns TOTP on.
func (q *Queries) UpsertUserTOTPSecret(ctx context.Context, arg UpsertUserTOTPSecretParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUserTOTPSecret, arg.UserID, arg.SecretCiphertext)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
