// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package sqlcgen

import (
	"context"
)

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, updated_at
FROM system_settings
WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT key, value, updated_at
FROM system_settings
ORDER BY key ASC
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key)
DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
RETURNING key, value, updated_at
`

type UpsertSystemSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Key, arg.Value)
	var i SystemSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
