// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthUserInTenant = `-- name: CreateAuthUserInTenant :one
INSERT INTO users (email, password_hash, role, permissions, status, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, role, permissions, status, created_at, updated_at, account_version, totp_enabled, tenant_id
`

type CreateAuthUserInTenantParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         pgtype.Text `json:"role"`
	Permissions  int64       `json:"permissions"`
	Status       string      `json:"status"`
	TenantID     string      `json:"tenant_id"`
}

func (q *Queries) CreateAuthUserInTenant(ctx context.Context, arg CreateAuthUserInTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, createAuthUserInTenant,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Permissions,
		arg.Status,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountVersion,
		&i.TotpEnabled,
		&i.TenantID,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (id, slug, name, status)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, status, created_at, updated_at
`

type CreateTenantParams struct {
	ID     string `json:"id"`
	Slug   string `json:"slug"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

// Tenant directory.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Status,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByIDInTenant = `-- name: GetAuthUserByIDInTenant :one

SELECT id, email, password_hash, role, permissions, status, created_at, updated_at, account_version, totp_enabled, tenant_id FROM users
WHERE tenant_id = $1 AND id = $2
`

type GetAuthUserByIDInTenantParams struct {
	TenantID string      `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Tenant-scoped user access, used by the tenancy feature's goAuth provider
// wrapper (goauth.TenantAwareUserProvider). The core auth queries never
// mention tenant_id; the column's default covers inserts made without it.
// The tenant predicate is enforced in SQL; a user in another tenant is not
// found.
func (q *Queries) GetAuthUserByIDInTenant(ctx context.Context, arg GetAuthUserByIDInTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByIDInTenant, arg.TenantID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountVersion,
		&i.TotpEnabled,
		&i.TenantID,
	)
	return i, err
}

const getAuthUserByLoginInTenant = `-- name: GetAuthUserByLoginInTenant :one
SELECT id, email, password_hash, role, permissions, status, created_at, updated_at, account_version, totp_enabled, tenant_id FROM users
WHERE tenant_id = $1 AND lower(email) = lower($2)
`

type GetAuthUserByLoginInTenantParams struct {
	TenantID string `json:"tenant_id"`
	Email    string `json:"email"`
}

// Identifiers are compared case-insensitively, like GetAuthUserByLogin. The
// tenant predicate is enforced in SQL; an identifier in another tenant is not
// found.
func (q *Queries) GetAuthUserByLoginInTenant(ctx context.Context, arg GetAuthUserByLoginInTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, getAuthUserByLoginInTenant, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Permissions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountVersion,
		&i.TotpEnabled,
		&i.TenantID,
	)
	return i, err
}

const getAuthUserTenant = `-- name: GetAuthUserTenant :one
SELECT tenant_id FROM users WHERE id = $1
`

func (q *Queries) GetAuthUserTenant(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAuthUserTenant, id)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, name, status, created_at, updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, status, created_at, updated_at
FROM tenants
WHERE slug = $1
`

// Slugs are stored lower-case (the subdomain resolver lower-cases the host
// label); callers pass a normalized slug. tenants.slug is UNIQUE.
func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, name, status, created_at, updated_at
FROM tenants
ORDER BY created_at ASC, id ASC
LIMIT $1
`

func (q *Queries) ListTenants(ctx context.Context, limit int32) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthUserPasswordHashInTenant = `-- name: UpdateAuthUserPasswordHashInTenant :one
UPDATE users SET password_hash = $3, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id
`

type UpdateAuthUserPasswordHashInTenantParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     string      `json:"tenant_id"`
	PasswordHash string      `json:"password_hash"`
}

// Tenant-scoped password write (goauth.TenantAwarePasswordUpdater). The tenant
// predicate is enforced in SQL; a user in another tenant matches no row, so
// the write is a not-found rather than a silent update.
func (q *Queries) UpdateAuthUserPasswordHashInTenant(ctx context.Context, arg UpdateAuthUserPasswordHashInTenantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateAuthUserPasswordHashInTenant, arg.ID, arg.TenantID, arg.PasswordHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
