// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webauthn_credentials.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :exec
INSERT INTO webauthn_credentials (
    credential_id, user_id, public_key, attestation_type, transports,
    user_present, user_verified, backup_eligible, backup_state, aaguid,
    sign_count, attachment, created_at, last_used_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateWebAuthnCredentialParams struct {
	CredentialID    []byte             `json:"credential_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	PublicKey       []byte             `json:"public_key"`
	AttestationType string             `json:"attestation_type"`
	Transports      []string           `json:"transports"`
	UserPresent     bool               `json:"user_present"`
	UserVerified    bool               `json:"user_verified"`
	BackupEligible  bool               `json:"backup_eligible"`
	BackupState     bool               `json:"backup_state"`
	Aaguid          []byte             `json:"aaguid"`
	SignCount       int64              `json:"sign_count"`
	Attachment      string             `json:"attachment"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, createWebAuthnCredential,
		arg.CredentialID,
		arg.UserID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transports,
		arg.UserPresent,
		arg.UserVerified,
		arg.BackupEligible,
		arg.BackupState,
		arg.Aaguid,
		arg.SignCount,
		arg.Attachment,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :one
DELETE FROM webauthn_credentials
WHERE user_id = $1 AND credential_id = $2
RETURNING credential_id
`

type DeleteWebAuthnCredentialParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CredentialID []byte      `json:"credential_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteWebAuthnCredential, arg.UserID, arg.CredentialID)
	var credential_id []byte
	err := row.Scan(&credential_id)
	return credential_id, err
}

const listWebAuthnCredentialsByUser = `-- name: ListWebAuthnCredentialsByUser :many
SELECT credential_id, user_id, public_key, attestation_type, transports,
       user_present, user_verified, backup_eligible, backup_state, aaguid,
       sign_count, attachment, created_at, last_used_at
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWebAuthnCredentialsByUser(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transports,
			&i.UserPresent,
			&i.UserVerified,
			&i.BackupEligible,
			&i.BackupState,
			&i.Aaguid,
			&i.SignCount,
			&i.Attachment,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :one
UPDATE webauthn_credentials
SET sign_count = $2, last_used_at = NOW()
WHERE credential_id = $1
RETURNING credential_id
`

type UpdateWebAuthnCredentialSignCountParams struct {
	CredentialID []byte `json:"credential_id"`
	SignCount    int64  `json:"sign_count"`
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updateWebAuthnCredentialSignCount, arg.CredentialID, arg.SignCount)
	var credential_id []byte
	err := row.Scan(&credential_id)
	return credential_id, err
}
