package modulesync

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedHeaderPrefix = "-- Code generated by modulesync. DO NOT EDIT.\n-- Source: "

// SourceFile describes one module-local SQL file sync mapping.
type SourceFile struct {
	// Module is the source module name.
	Module string
	// Source is the module-local SQL file path.
	Source string
	// Target is the synced root-level SQL file path.
	Target string
}

// Sync copies module-local SQL files into root db/schema and db/queries.
func Sync(workspaceRoot string) error {
	files, err := collect(workspaceRoot)
	if err != nil {
		return err
	}

	managed := make(map[string]struct{}, len(files))
	for _, file := range files {
		if err := syncFile(file); err != nil {
			return err
		}
		managed[file.Target] = struct{}{}
	}

	if err := cleanupManaged(filepath.Join(workspaceRoot, "db", "schema"), managed); err != nil {
		return err
	}
	if err := cleanupManaged(filepath.Join(workspaceRoot, "db", "queries"), managed); err != nil {
		return err
	}
	return nil
}

func collect(workspaceRoot string) ([]SourceFile, error) {
	modulesDir := filepath.Join(workspaceRoot, "internal", "modules")
	entries, err := os.ReadDir(modulesDir)
	if err != nil {
		return nil, fmt.Errorf("read modules directory: %w", err)
	}

	files := make([]SourceFile, 0, len(entries)*2)
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		moduleName := entry.Name()
		moduleDBDir := filepath.Join(modulesDir, moduleName, "db")
		if _, err := os.Stat(moduleDBDir); errorsIsNotExist(err) {
			continue
		} else if err != nil {
			return nil, fmt.Errorf("stat module db directory: %w", err)
		}

		schemaSource := filepath.Join(moduleDBDir, "schema.sql")
		if _, err := os.Stat(schemaSource); err == nil {
			files = append(files, SourceFile{
				Module: moduleName,
				Source: schemaSource,
				Target: filepath.Join(workspaceRoot, "db", "schema", moduleName+".sql"),
			})
		} else if !errorsIsNotExist(err) {
			return nil, fmt.Errorf("stat schema source: %w", err)
		}

		querySource := filepath.Join(moduleDBDir, "queries.sql")
		if _, err := os.Stat(querySource); err == nil {
			files = append(files, SourceFile{
				Module: moduleName,
				Source: querySource,
				Target: filepath.Join(workspaceRoot, "db", "queries", moduleName+".sql"),
			})
		} else if !errorsIsNotExist(err) {
			return nil, fmt.Errorf("stat query source: %w", err)
		}
	}

	sort.Slice(files, func(i, j int) bool {
		if files[i].Target == files[j].Target {
			return files[i].Source < files[j].Source
		}
		return files[i].Target < files[j].Target
	})
	return files, nil
}

func syncFile(file SourceFile) error {
	content, err := os.ReadFile(file.Source)
	if err != nil {
		return fmt.Errorf("read source %s: %w", file.Source, err)
	}

	if err := os.MkdirAll(filepath.Dir(file.Target), 0o755); err != nil {
		return fmt.Errorf("create target directory: %w", err)
	}

	header := generatedHeaderPrefix + relativeSource(file.Source) + "\n\n"
	if err := os.WriteFile(file.Target, append([]byte(header), content...), 0o644); err != nil {
		return fmt.Errorf("write target %s: %w", file.Target, err)
	}
	return nil
}

func cleanupManaged(dir string, managed map[string]struct{}) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if errorsIsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read directory %s: %w", dir, err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		target := filepath.Join(dir, entry.Name())
		if _, ok := managed[target]; ok {
			continue
		}

		content, err := os.ReadFile(target)
		if err != nil {
			return fmt.Errorf("read managed target %s: %w", target, err)
		}
		if strings.HasPrefix(string(content), generatedHeaderPrefix) {
			if err := os.Remove(target); err != nil {
				return fmt.Errorf("remove stale managed target %s: %w", target, err)
			}
		}
	}
	return nil
}

func relativeSource(path string) string {
	slashPath := filepath.ToSlash(path)
	needle := "/internal/modules/"
	idx := strings.Index(slashPath, needle)
	if idx >= 0 {
		return slashPath[idx+1:]
	}
	return slashPath
}

func errorsIsNotExist(err error) bool {
	return err != nil && os.IsNotExist(err)
}
