package auth

import (
	"context"
	"errors"
	"fmt"

	goauth "github.com/MrEthical07/goAuth"
	"github.com/MrEthical07/superapi/internal/core/db/sqlcgen"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// SQLCUserProvider is the DB-backed UserProvider for goAuth.
// Generated by authgen — do not edit manually.
type SQLCUserProvider struct {
	queries *sqlcgen.Queries
}

// NewSQLCUserProvider creates a DB-backed user provider.
func NewSQLCUserProvider(queries *sqlcgen.Queries) *SQLCUserProvider {
	return &SQLCUserProvider{queries: queries}
}

func (p *SQLCUserProvider) GetUserByIdentifier(identifier string) (goauth.UserRecord, error) {
	row, err := p.queries.GetAuthUserByLogin(context.Background(), identifier)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return goauth.UserRecord{}, goauth.ErrUserNotFound
		}
		return goauth.UserRecord{}, fmt.Errorf("get user by identifier: %w", err)
	}
	return mapUserToRecord(row), nil
}

func (p *SQLCUserProvider) GetUserByID(userID string) (goauth.UserRecord, error) {
	var pgID pgtype.UUID
	if err := pgID.Scan(userID); err != nil {
		return goauth.UserRecord{}, goauth.ErrUserNotFound
	}
	row, err := p.queries.GetAuthUserByID(context.Background(), pgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return goauth.UserRecord{}, goauth.ErrUserNotFound
		}
		return goauth.UserRecord{}, fmt.Errorf("get user by id: %w", err)
	}
	return mapUserToRecord(row), nil
}

func (p *SQLCUserProvider) UpdatePasswordHash(userID string, newHash string) error {
	var pgID pgtype.UUID
	if err := pgID.Scan(userID); err != nil {
		return goauth.ErrUserNotFound
	}
	return p.queries.UpdateAuthUserPasswordHash(context.Background(), sqlcgen.UpdateAuthUserPasswordHashParams{
		ID: pgID,
		PasswordHash: newHash,
	})
}

func (p *SQLCUserProvider) CreateUser(ctx context.Context, input goauth.CreateUserInput) (goauth.UserRecord, error) {
	row, err := p.queries.CreateAuthUser(ctx, sqlcgen.CreateAuthUserParams{
		Email: input.Identifier,
		PasswordHash: input.PasswordHash,
		Role: pgtype.Text{String: input.Role, Valid: input.Role != ""},
		Permissions: 0,
		Status: mapAccountStatusToString(input.Status),
	})
	if err != nil {
		return goauth.UserRecord{}, fmt.Errorf("create user: %w", err)
	}
	return mapUserToRecord(row), nil
}

func (p *SQLCUserProvider) UpdateAccountStatus(ctx context.Context, userID string, status goauth.AccountStatus) (goauth.UserRecord, error) {
	var pgID pgtype.UUID
	if err := pgID.Scan(userID); err != nil {
		return goauth.UserRecord{}, goauth.ErrUserNotFound
	}
	row, err := p.queries.UpdateAuthUserStatus(ctx, sqlcgen.UpdateAuthUserStatusParams{
		ID: pgID,
		Status: mapAccountStatusToString(status),
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return goauth.UserRecord{}, goauth.ErrUserNotFound
		}
		return goauth.UserRecord{}, fmt.Errorf("update account status: %w", err)
	}
	return mapUserToRecord(row), nil
}

// TOTP stubs — implement when MFA is needed.
func (p *SQLCUserProvider) GetTOTPSecret(_ context.Context, _ string) (*goauth.TOTPRecord, error) {
	return nil, goauth.ErrUnauthorized
}
func (p *SQLCUserProvider) EnableTOTP(_ context.Context, _ string, _ []byte) error {
	return goauth.ErrUnauthorized
}
func (p *SQLCUserProvider) DisableTOTP(_ context.Context, _ string) error {
	return goauth.ErrUnauthorized
}
func (p *SQLCUserProvider) MarkTOTPVerified(_ context.Context, _ string) error {
	return goauth.ErrUnauthorized
}
func (p *SQLCUserProvider) UpdateTOTPLastUsedCounter(_ context.Context, _ string, _ int64) error {
	return goauth.ErrUnauthorized
}

// Backup code stubs — implement when MFA is needed.
func (p *SQLCUserProvider) GetBackupCodes(_ context.Context, _ string) ([]goauth.BackupCodeRecord, error) {
	return nil, goauth.ErrUnauthorized
}
func (p *SQLCUserProvider) ReplaceBackupCodes(_ context.Context, _ string, _ []goauth.BackupCodeRecord) error {
	return goauth.ErrUnauthorized
}
func (p *SQLCUserProvider) ConsumeBackupCode(_ context.Context, _ string, _ [32]byte) (bool, error) {
	return false, goauth.ErrUnauthorized
}

// --- Mapping helpers ---

func mapUserToRecord(row sqlcgen.User) goauth.UserRecord {
	return goauth.UserRecord{
		UserID:     formatUUID(row.ID),
		Identifier: row.Email,
		PasswordHash: row.PasswordHash,
		Role:         row.Role.String,
		Status:       parseAccountStatus(row.Status),
	}
}

func formatUUID(u pgtype.UUID) string {
	if !u.Valid {
		return ""
	}
	b := u.Bytes
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}


func mapAccountStatusToString(s goauth.AccountStatus) string {
	switch s {
	case goauth.AccountActive:
		return "active"
	case goauth.AccountPendingVerification:
		return "pending_verification"
	case goauth.AccountDisabled:
		return "disabled"
	case goauth.AccountLocked:
		return "locked"
	case goauth.AccountDeleted:
		return "deleted"
	default:
		return "active"
	}
}

func parseAccountStatus(s string) goauth.AccountStatus {
	switch s {
	case "active":
		return goauth.AccountActive
	case "pending_verification":
		return goauth.AccountPendingVerification
	case "disabled":
		return goauth.AccountDisabled
	case "locked":
		return goauth.AccountLocked
	case "deleted":
		return goauth.AccountDeleted
	default:
		return goauth.AccountActive
	}
}
